Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
password_widget = widgets.VBox(children=[helpful_title, password_text, password_length])
password_widget
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTraitError[0m                                Traceback (most recent call last)
Cell [1;32mIn[3], line 1[0m
[1;32m----> 1[0m password_widget [38;5;241m=[39m widgets[38;5;241m.[39mVBox(children[38;5;241m=[39m[helpful_title, password_text, password_length])
[0;32m      2[0m password_widget

File [1;32mD:\Anaconda3\Lib\site-packages\ipywidgets\widgets\widget_box.py:64[0m, in [0;36mBox.__init__[1;34m(self, children, **kwargs)[0m
[0;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, children[38;5;241m=[39m(), [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m     63[0m     kwargs[[38;5;124m'[39m[38;5;124mchildren[39m[38;5;124m'[39m] [38;5;241m=[39m children
[1;32m---> 64[0m     [38;5;28msuper[39m(Box, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m([38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m     65[0m     [38;5;28mself[39m[38;5;241m.[39mon_displayed(Box[38;5;241m.[39m_fire_children_displayed)

File [1;32mD:\Anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py:478[0m, in [0;36mWidget.__init__[1;34m(self, **kwargs)[0m
[0;32m    476[0m [38;5;250m[39m[38;5;124;03m"""Public constructor"""[39;00m
[0;32m    477[0m [38;5;28mself[39m[38;5;241m.[39m_model_id [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m'[39m[38;5;124mmodel_id[39m[38;5;124m'[39m, [38;5;28;01mNone[39;00m)
[1;32m--> 478[0m [38;5;28msuper[39m(Widget, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m([38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    480[0m Widget[38;5;241m.[39m_call_widget_constructed([38;5;28mself[39m)
[0;32m    481[0m [38;5;28mself[39m[38;5;241m.[39mopen()

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:1355[0m, in [0;36mHasTraits.__init__[1;34m(self, *args, **kwargs)[0m
[0;32m   1353[0m [38;5;28;01mfor[39;00m key, value [38;5;129;01min[39;00m kwargs[38;5;241m.[39mitems():
[0;32m   1354[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mhas_trait(key):
[1;32m-> 1355[0m         [38;5;28msetattr[39m([38;5;28mself[39m, key, value)
[0;32m   1356[0m         changes[key] [38;5;241m=[39m Bunch(
[0;32m   1357[0m             name[38;5;241m=[39mkey,
[0;32m   1358[0m             old[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m   (...)[0m
[0;32m   1361[0m             [38;5;28mtype[39m[38;5;241m=[39m[38;5;124m"[39m[38;5;124mchange[39m[38;5;124m"[39m,
[0;32m   1362[0m         )
[0;32m   1363[0m     [38;5;28;01melse[39;00m:
[0;32m   1364[0m         [38;5;66;03m# passthrough args that don't set traits to super[39;00m

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:716[0m, in [0;36mTraitType.__set__[1;34m(self, obj, value)[0m
[0;32m    714[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mread_only:
[0;32m    715[0m     [38;5;28;01mraise[39;00m TraitError([38;5;124m'[39m[38;5;124mThe [39m[38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m"[39m[38;5;124m trait is read-only.[39m[38;5;124m'[39m [38;5;241m%[39m [38;5;28mself[39m[38;5;241m.[39mname)
[1;32m--> 716[0m [38;5;28mself[39m[38;5;241m.[39mset(obj, value)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:690[0m, in [0;36mTraitType.set[1;34m(self, obj, value)[0m
[0;32m    689[0m [38;5;28;01mdef[39;00m [38;5;21mset[39m([38;5;28mself[39m, obj: HasTraits, value: S) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m--> 690[0m     new_value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate(obj, value)
[0;32m    691[0m     [38;5;28;01massert[39;00m [38;5;28mself[39m[38;5;241m.[39mname [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m    692[0m     [38;5;28;01mtry[39;00m:

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:722[0m, in [0;36mTraitType._validate[1;34m(self, obj, value)[0m
[0;32m    720[0m     [38;5;28;01mreturn[39;00m value
[0;32m    721[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m, [38;5;124m"[39m[38;5;124mvalidate[39m[38;5;124m"[39m):
[1;32m--> 722[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mvalidate(obj, value)
[0;32m    723[0m [38;5;28;01mif[39;00m obj[38;5;241m.[39m_cross_validation_lock [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m:
[0;32m    724[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_cross_validate(obj, value)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:3482[0m, in [0;36mContainer.validate[1;34m(self, obj, value)[0m
[0;32m   3479[0m [38;5;28;01mif[39;00m value [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m   3480[0m     [38;5;28;01mreturn[39;00m value
[1;32m-> 3482[0m value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mvalidate_elements(obj, value)
[0;32m   3484[0m [38;5;28;01mreturn[39;00m t[38;5;241m.[39mcast(T, value)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:3494[0m, in [0;36mContainer.validate_elements[1;34m(self, obj, value)[0m
[0;32m   3492[0m     v [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_trait[38;5;241m.[39m_validate(obj, v)
[0;32m   3493[0m [38;5;28;01mexcept[39;00m TraitError [38;5;28;01mas[39;00m error:
[1;32m-> 3494[0m     [38;5;28mself[39m[38;5;241m.[39merror(obj, v, error)
[0;32m   3495[0m [38;5;28;01melse[39;00m:
[0;32m   3496[0m     validated[38;5;241m.[39mappend(v)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:810[0m, in [0;36mTraitType.error[1;34m(self, obj, value, error, info)[0m
[0;32m    801[0m         [38;5;28;01melse[39;00m:
[0;32m    802[0m             error[38;5;241m.[39margs [38;5;241m=[39m (
[0;32m    803[0m                 [38;5;124m"[39m[38;5;124mThe [39m[38;5;124m'[39m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;124m trait contains [39m[38;5;132;01m{}[39;00m[38;5;124m which [39m[38;5;124m"[39m [38;5;124m"[39m[38;5;124mexpected [39m[38;5;132;01m{}[39;00m[38;5;124m, not [39m[38;5;132;01m{}[39;00m[38;5;124m.[39m[38;5;124m"[39m[38;5;241m.[39mformat(
[0;32m    804[0m                     [38;5;28mself[39m[38;5;241m.[39mname,
[1;32m   (...)[0m
[0;32m    808[0m                 ),
[0;32m    809[0m             )
[1;32m--> 810[0m     [38;5;28;01mraise[39;00m error
[0;32m    812[0m [38;5;66;03m# this trait caused an error[39;00m
[0;32m    813[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mname [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m    814[0m     [38;5;66;03m# this is not the root trait[39;00m

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:3492[0m, in [0;36mContainer.validate_elements[1;34m(self, obj, value)[0m
[0;32m   3490[0m [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m value:
[0;32m   3491[0m     [38;5;28;01mtry[39;00m:
[1;32m-> 3492[0m         v [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_trait[38;5;241m.[39m_validate(obj, v)
[0;32m   3493[0m     [38;5;28;01mexcept[39;00m TraitError [38;5;28;01mas[39;00m error:
[0;32m   3494[0m         [38;5;28mself[39m[38;5;241m.[39merror(obj, v, error)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:722[0m, in [0;36mTraitType._validate[1;34m(self, obj, value)[0m
[0;32m    720[0m     [38;5;28;01mreturn[39;00m value
[0;32m    721[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m, [38;5;124m"[39m[38;5;124mvalidate[39m[38;5;124m"[39m):
[1;32m--> 722[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mvalidate(obj, value)
[0;32m    723[0m [38;5;28;01mif[39;00m obj[38;5;241m.[39m_cross_validation_lock [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m:
[0;32m    724[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_cross_validate(obj, value)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:2311[0m, in [0;36mInstance.validate[1;34m(self, obj, value)[0m
[0;32m   2309[0m     [38;5;28;01mreturn[39;00m t[38;5;241m.[39mcast(T, value)
[0;32m   2310[0m [38;5;28;01melse[39;00m:
[1;32m-> 2311[0m     [38;5;28mself[39m[38;5;241m.[39merror(obj, value)

File [1;32mD:\Anaconda3\Lib\site-packages\traitlets\traitlets.py:815[0m, in [0;36mTraitType.error[1;34m(self, obj, value, error, info)[0m
[0;32m    812[0m [38;5;66;03m# this trait caused an error[39;00m
[0;32m    813[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mname [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m    814[0m     [38;5;66;03m# this is not the root trait[39;00m
[1;32m--> 815[0m     [38;5;28;01mraise[39;00m TraitError(value, info [38;5;129;01mor[39;00m [38;5;28mself[39m[38;5;241m.[39minfo(), [38;5;28mself[39m)
[0;32m    817[0m [38;5;66;03m# this is the root trait[39;00m
[0;32m    818[0m [38;5;28;01mif[39;00m obj [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

[1;31mTraitError[0m: The 'children' trait of a VBox instance contains an Instance of a TypedTuple which expected a Widget, not the int 0.

