Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\Anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from my_application import MyApplication
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmy_application[39;00m [38;5;28;01mimport[39;00m MyApplication

File [1;32m~\Desktop\jupyterBook\widgets-book\widgets-book\05.Build-complex-libs\my_application\__init__.py:1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mapplication[39;00m [38;5;28;01mimport[39;00m MyApplication
[0;32m      3[0m __all__ [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mMyApplication[39m[38;5;124m"[39m]

File [1;32m~\Desktop\jupyterBook\widgets-book\widgets-book\05.Build-complex-libs\my_application\application.py:3[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m display
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m HBox, VBox, HTML
[1;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipydatagrid[39;00m [38;5;28;01mimport[39;00m DataGrid
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mbqplot[39;00m [38;5;28;01mimport[39;00m CATEGORY10
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mchart[39;00m [38;5;28;01mimport[39;00m Chart

[1;31mModuleNotFoundError[0m: No module named 'ipydatagrid'

